### PR TITLE
fixed devise 4.2 deprication warnings by using bypass_sign_in

### PR DESCRIPTION
**Pull request by mikedebock**
Use bypass_sign_in if using Devise 4.2.
If using older version of Devise use legacy call sign_in(user, bypass: true)

### CODE REVIEW

**Comment by oivoodoo** [comment]
@mikedebock Going to review it as soon as possible and merge it in case it's not breaking change and tests will pass for me. Thank you!

**Comment by oivoodoo** [comment]
@mikedebock Thank you! :shipit:

**Comment by mikedebock** [comment]
Thank you for merging! Would you create new release v1.0.8?

**Comment by oivoodoo** [comment]
@mikedebock I've released devise_masquerade 0.1.8 version. Thank you!

**Pull request merged**
