### PR TITLE
Refactor to use Signed GlobalIDs instead of Rails cache

### PR DESCRIPTION
**Pull request by oivoodoo**

### CODE REVIEW

**Comment by oivoodoo** [comment]
Hi @excid3 

Going to merge your changes to develop a branch and give it a try locally.

it looks like it's valuable change to skip `Rails.cache`, sorry for delay on it.

Thank you!

**Comment by marckohlbrugge** [comment]
Just wanted to say thanks as this PR made using the gem possible for me. Hope it gets merged into master soon 🙌

**Comment by excid3** [comment]
I think it did get released, but wasn't sure. Thanks for working on this gem @oivoodoo 👍

**Comment by marckohlbrugge** [comment]
@excid3 Ah yes, you're right. It did get merged in, but unfortunately [a later commit added back the Rails Cache dependency](https://github.com/oivoodoo/devise_masquerade/search?q=Rails.cache). Both the latest release and master don't work properly without a cache store.

@oivoodoo Is there any chance you could make the Rails cache store optional again? Thanks for all your work 🙌

**Pull request merged**
